export const TransferConstants = {
    TRANSFER_LOCAL_PENDING: "TRANSFER_PENDING",
    TRANSFER_LOCAL_SUCCESS: "TRANSFER_SUCCESS",
    TRANSFER_LOCAL_ERROR: "TRANSFER_ERROR",
    
    TRANSFER_INTER_PENDING: "TRANSFER_INTER_PENDING",
    TRANSFER_INTER_SUCCESS: "TRANSFER_INTER_SUCCESS",
    TRANSFER_INTER_ERROR: "TRANSFER_INTER_ERROR",

    OTP_PENDING: "OTP_PENDING",
    OTP_SUCCESS: "OTP_SUCCESS",
    OTP_ERROR: "OTP_ERROR",

    FIND_RECEIVER_PENDING: "FIND_RECEIVER_PENDING",
    FIND_RECEIVER_SUCCESS: "FIND_RECEIVER_SUCCESS",
    FIND_RECEIVER_ERROR: "FIND_RECEIVER_ERROR",

    GET_REMIND_LIST_PENDING: "GET_REMIND_LIST_PENDING",
    GET_REMIND_LIST_SUCCESS: "GET_REMIND_LIST_SUCCESS",
    GET_REMIND_LIST_ERROR: "GET_REMIND_LIST_ERROR",

    SAVE_REMIND_LIST_PENDING: "SAVE_REMIND_LIST_PENDING",
    SAVE_REMIND_LIST_SUCCESS: "SAVE_REMIND_LIST_SUCCESS",
    SAVE_REMIND_LIST_ERROR: "SAVE_REMIND_LIST_ERROR",
}