export const EmpConstants = {

    LOGIN_REQUEST : 'LOGIN_EMP_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_EMP_SUCCESS',
    LOGIN_ERROR : 'LOGIN_EMP_ERROR',
    
    LOGOUT : "LOGOUT_EMP",

    ADD_CUSTOMER_PENDING: 'ADD_CUSTOMER_PENDING',
    ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
    ADD_CUSTOMER_ERROR: 'ADD_CUSTOMER_ERROR',

    FIND_CUSTOMER_PENDING: 'FIND_CUSTOMER_PENDING',
    FIND_CUSTOMER_SUCCESS: 'FIND_CUSTOMER_SUCCESS',
    FIND_CUSTOMER_ERROR: 'FIND_CUSTOMER_ERROR',

    ADD_MONEY_TO_CUSTOMER_PENDING: 'ADD_MONEY_TO_CUSTOMER_PENDING',
    ADD_MONEY_TO_CUSTOMER_SUCCESS: 'ADD_MONEY_TO_CUSTOMER_SUCCESS',
    ADD_MONEY_TO_CUSTOMER_ERROR: 'ADD_MONEY_TO_CUSTOMER_ERROR',

    FIND_TRANSACTION_HISTORY_PENDING: 'FIND_TRANSACTION_HISTORY_PENDING',
    FIND_TRANSACTION_HISTORY_SUCCESS: 'FIND_TRANSACTION_HISTORY_SUCCESS',
    FIND_TRANSACTION_HISTORY_ERROR: 'FIND_TRANSACTION_HISTORY_ERROR',
}