export const AdminConstants = {

    LOGIN_REQUEST : 'LOGIN_ADMIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_ADMIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ADMIN_ERROR',
    
    LOGOUT : "LOGOUT_ADMIN",

    GET_ALL_EMPLOYEE_PENDING: 'GET_ALL_EMPLOYEE_PENDING',
    GET_ALL_EMPLOYEE_SUCCESS: 'GET_ALL_EMPLOYEE_SUCCESS',
    GET_ALL_EMPLOYEE_ERROR: 'GET_ALL_EMPLOYEE_ERROR',

    CREATE_EMPLOYEE_PENDING: 'CREATE_EMPLOYEE_PENDING',
    CREATE_EMPLOYEE_SUCCESS: 'CREATE_EMPLOYEE_SUCCESS',
    CREATE_EMPLOYEE_ERROR: 'CREATE_EMPLOYEE_ERROR',

    UPDATE_PASSWORD_EMPLOYEE_PENDING: 'UPDATE_PASSWORD_EMPLOYEE_PENDING',
    UPDATE_PASSWORD_EMPLOYEE_SUCCESS: 'UPDATE_PASSWORD_EMPLOYEE_SUCCESS',
    UPDATE_PASSWORD_EMPLOYEE_ERROR: 'UPDATE_PASSWORD_EMPLOYEE_ERROR',
}